version: 1
recover_revenue_enabled: false
messaging_enabled: true
promise_tracking_enabled: true
campaigns_enabled: true
mode: fully_automatic
max_automatic_recovery_inr: 5000
merchant_alerts: exceptions_only
enabled_at: '2026-08-30T18:54:25.629934+00:00'
paused_at: '2026-08-30T18:54:33.172319+00:00'
